-- INSERT INTO hotel.Title(title) VALUES("Mr"),("Mrs"),("Miss"),("Ms"),("Dr");
/*INSERT INTO hotel.Country(Name) Values 
("Afghanistan"),
("Albania"),
("Algeria"),
("Andorra"),
("Angola"),
("Antigua and Barbuda"),
("Argentina"),
("Armenia"),
("Australia"),
("Austria"),
("Azerbaijan"),
("Bahamas, The"),
("Bahrain"),
("Bangladesh"),
("Barbados"),
("Belarus"),
("Belgium"),
("Belize"),
("Benin"),
("Bhutan"),
("Bolivia"),
("Bosnia and Herzegovina"),
("Botswana"),
("Brazil"),
("Brunei"),
("Bulgaria"),
("Burkina Faso"),
("Burma"),
("Burundi"),
("Cambodia"),
("Cameroon"),
("Canada"),
("Cape Verde"),
("Central Africa"),
("Chad"),
("Chile"),
("China"),
("Colombia"),
("Comoros"),
("Congo, Democratic Republic of the"),
("Costa Rica"),
("Cote dIvoire"),
("Crete"),
("Croatia"),
("Cuba"),
("Cyprus"),
("Czech Republic"),
("Denmark"),
("Djibouti"),
("Dominican Republic"),
("East Timor"),
("Ecuador"),
("Egypt"),
("El Salvador"),
("Equatorial Guinea"),
("Eritrea"),
("Estonia"),
("Ethiopia"),
("Fiji"),
("Finland"),
("France"),
("Gabon"),
("Gambia, The"),
("Georgia"),
("Germany"),
("Ghana"),
("Greece"),
("Grenada"),
("Guadeloupe"),
("Guatemala"),
("Guinea"),
("Guinea-Bissau"),
("Guyana"),
("Haiti"),
("Holy See"),
("Honduras"),
("Hong Kong"),
("Hungary"),
("Iceland"),
("India"),
("Indonesia"),
("Iran"),
("Iraq"),
("Ireland"),
("Israel"),
("Italy"),
("Ivory Coast"),
("Jamaica"),
("Japan"),
("Jordan"),
("Kazakhstan"),
("Kenya"),
("Kiribati"),
("Korea, North"),
("Korea, South"),
("Kosovo"),
("Kuwait"),
("Kyrgyzstan"),
("Laos"),
("Latvia"),
("Lebanon"),
("Lesotho"),
("Liberia"),
("Libya"),
("Liechtenstein"),
("Lithuania"),
("Macau"),
("Macedonia"),
("Madagascar"),
("Malawi"),
("Malaysia"),
("Maldives"),
("Mali"),
("Malta"),
("Marshall Islands"),
("Mauritania"),
("Mauritius"),
("Mexico"),
("Micronesia"),
("Moldova"),
("Monaco"),
("Mongolia"),
("Montenegro"),
("Morocco"),
("Mozambique"),
("Namibia"),
("Nauru"),
("Nepal"),
("Netherlands"),
("New Zealand"),
("Nicaragua"),
("Niger"),
("Nigeria"),
("North Korea"),
("Norway"),
("Oman"),
("Pakistan"),
("Palau"),
("Panama"),
("Papua New Guinea"),
("Paraguay"),
("Peru"),
("Philippines"),
("Poland"),
("Portugal"),
("Qatar"),
("Romania"),
("Russia"),
("Rwanda"),
("Saint Lucia"),
("Saint Vincent and the Grenadines"),
("Samoa"),
("San Marino"),
("Sao Tome and Principe"),
("Saudi Arabia"),
("Scotland"),
("Senegal"),
("Serbia"),
("Seychelles"),
("Sierra Leone"),
("Singapore"),
("Slovakia"),
("Slovenia"),
("Solomon Islands"),
("Somalia"),
("South Africa"),
("South Korea"),
("Spain"),
("Sri Lanka"),
("Sudan"),
("Suriname"),
("Swaziland"),
("Sweden"),
("Switzerland"),
("Syria"),
("Taiwan"),
("Tajikistan"),
("Tanzania"),
("Thailand"),
("Tibet"),
("Timor-Leste"),
("Togo"),
("Tonga"),
("Trinidad and Tobago"),
("Tunisia"),
("Turkey"),
("Turkmenistan"),
("Tuvalu"),
("Uganda"),
("Ukraine"),
("United Arab Emirates"),
("United Kingdom"),
("United States"),
("Uruguay"),
("Uzbekistan"),
("Vanuatu"),
("Venezuela"),
("Vietnam"),
("Yemen"),
("Zambia"),
("Zimbabwe");*/

-- insert into hotel.CardType (type) values ("VISA"),("MasterCard");

-- insert into hotel.PaymentMethod(method) values ("Cash"),("Card");

-- insert into hotel.PhoneType(type) values ("Home"),("Mobile"),("Work");

-- insert into hotel.ReservationType(Name) values ("Phone"),("Application"),("Website");

-- insert into hotel.RoomType(Name,Price,Description) values ("Standard",40,"Our Standard Room"),("Premium",60,"A better room"),("Suite",100,"Best Room Ever");

-- insert into hotel.Customer(TitleID,FirstName,LastName,BirthDate,Email,CountryID) Values
-- (4,"Katerina","Mpelmezou","1985-09-12","cathm247@yahoo.com",67),
-- (2,"Giorgos","Paschos","1991-07-22","ntelalis@gmail.com",67);

-- insert into hotel.Account(CustomerID,Email,Hash) values 
-- (1,"cathm247@yahoo.com","0011katerina"),
-- (2,"ntelalis@gmail.com","0011giorgos");